name: ethereum_address
description: A dart library to generate, checksum, and validate Ethereum addresses
version: 1.0.1
homepage: https://github.com/petejkim/dart-ethereum_address

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  convert: ^2.1.1
  pointycastle: 
    git:
      url: https://github.com/jbdtky/pc-dart.git
      ref: master

dev_dependencies:
  test: ^1.9.4
